apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: research-ibis-x
build:
  # Pas de defaultRepo global
  tagPolicy:
    sha256: {}
  # Configuration pour optimiser le cache mais permettre le pull des images manquantes
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
  artifacts:
    # Noms d'images de base SANS préfixe
    - image: ibis-x-api-gateway
      context: api-gateway
      docker: 
        dockerfile: Dockerfile
        # Optimiser le cache Docker
        noCache: false
        pullParent: false # Ne pas re-puller les images parentes si elles existent déjà
    - image: service-selection
      context: .  # Utilise le répertoire racine comme contexte pour accéder à common/
      docker: 
        dockerfile: service-selection/Dockerfile
        noCache: false
        pullParent: false # Ne pas re-puller les images parentes si elles existent déjà
    - image: frontend
      context: frontend
      # Définir buildArgs pour l'environnement par défaut (local)
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false # Ne pas re-puller les images parentes si elles existent déjà
        buildArgs:
          ANGULAR_ENV: development

deploy:
  kubectl: {}
profiles:
  - name: local
    # Utiliser Kustomize avec l'overlay minikube pour avoir les patches corrects
    manifests:
      kustomize:
        buildArgs:
          - --load-restrictor=LoadRestrictionsNone
        paths:
          - k8s/overlays/minikube
    # Configuration explicite du Port Forwarding
    portForward:
      # Frontend sur localhost:8080
      - resourceType: service
        resourceName: frontend # Nom du service K8s du frontend
        namespace: ibis-x
        port: 80 # Port interne du service
        localPort: 8080 # Port sur votre machine locale
      # API Gateway sur localhost:9000
      - resourceType: service
        resourceName: api-gateway-service # Nom du service K8s API Gateway
        namespace: ibis-x
        port: 80 # Port interne du service
        localPort: 9000 # Port sur votre machine locale
      - resourceType: service
        resourceName: minio-service
        namespace: ibis-x
        port: 6700
        localPort: 6700
      - resourceType: service
        resourceName: minio-service
        namespace: ibis-x
        port: 6701
        localPort: 6701

  - name: azure
    # Utiliser des patches pour modifier les noms d'images ET les buildArgs pour ce profil
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: ibisprodacr.azurecr.io/ibis-x-api-gateway
      - op: replace
        path: /build/artifacts/1/image
        value: ibisprodacr.azurecr.io/service-selection
      - op: replace
        path: /build/artifacts/2/image
        value: ibisprodacr.azurecr.io/frontend
      # Ajouter un patch pour surcharger les buildArgs du frontend pour Azure
      - op: add # Ou 'replace' si buildArgs existe déjà au path exact
        path: /build/artifacts/2/docker/buildArgs # Index 2 pour l'artefact frontend
        value:
          ANGULAR_ENV: production
    manifests:
      kustomize:
        # Changer le chemin pour exécuter Kustomize depuis le dossier k8s
        # en ciblant l'overlay azure.
        buildArgs:
          - --load-restrictor=LoadRestrictionsNone # Autorise explicitement la lecture en dehors du répertoire racine de Kustomize
        paths:
          - k8s/overlays/azure
    # Utilise le deploy kubectl global
