apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: ibis-x
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP 
