apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: exai
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 6700
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 6701
      targetPort: 9001
  type: ClusterIP 