apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ibis-x-ingress
  namespace: ibis-x # Assurez-vous que ce namespace est correct ou retirez-le si vous utilisez 'default'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # CORS Configuration
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-max-age: "86400"
    # Configuration spéciale : Permettre CORS seulement depuis les domaines de production et locaux
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://ibis-x.fr,https://www.ibis-x.fr,http://localhost:8080,http://localhost:9000"
    # Certificats Let's Encrypt (Cert-Manager)
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Redirection www -> sans www
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($host = 'www.ibis-x.fr') {
        return 301 https://ibis-x.fr$request_uri;
      }
spec:
  tls:
  - hosts:
    - api.ibis-x.fr # Votre nom d'hôte
    - ibis-x.fr   # Votre domaine racine
    - www.ibis-x.fr  # Redirection www
    secretName: ibis-x-tls  # Secret pour les certificats TLS
  rules:
  # API Backend
  - host: api.ibis-x.fr # Votre nom d'hôte
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 80
  # Frontend
  - host: ibis-x.fr # Votre domaine racine
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  # Configuration TLS pour certificats HTTPS via cert-manager
  # Les certificats TLS sont automatiquement fournis par Let's Encrypt
  # grâce aux annotations cert-manager définies plus haut
  - hosts:
    - api.ibis-x.fr # Host pour l'API
    - ibis-x.fr   # Host pour le Frontend
    - www.ibis-x.fr  # Host pour la redirection www
    secretName: ibis-x-tls # <-- Décommenté et Nommé
