apiVersion: v1
kind: Service
metadata:
  name: service-selection-service
  namespace: ibis-x
spec:
  selector:
    app: service-selection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort
