apiVersion: v1
kind: Secret
metadata:
  name: storage-secrets
  namespace: exai
type: Opaque
data:
  # Configuration MinIO (développement local)
  # Encodé en Base64 : http://minio-service.exai.svc.cluster.local:9000
  minio-endpoint: aHR0cDovL21pbmlvLXNlcnZpY2UuZXhhaS5zdmMuY2x1c3Rlci5sb2NhbDo5MDAw
  # Encodé en Base64 : minioadmin
  minio-access-key: bWluaW9hZG1pbg==
  # Encodé en Base64 : minioadmin
  minio-secret-key: bWluaW9hZG1pbg==
  # Encodé en Base64 : exai-datasets
  minio-bucket-name: ZXhhaS1kYXRhc2V0cw==
  
  # Configuration Azure Storage (production) - placeholders encodés
  # Encodé en Base64 : your-storage-account
  azure-storage-account-name: eW91ci1zdG9yYWdlLWFjY291bnQ=
  # Encodé en Base64 : your-storage-key
  azure-storage-account-key: eW91ci1zdG9yYWdlLWtleQ==
  # Encodé en Base64 : exai-datasets
  azure-container-name: ZXhhaS1kYXRhc2V0cw==
  
  # Compatibilité avec l'ancien format (pour éviter les breaks)
  # Encodé en Base64 : minioadmin  
  access-key: bWluaW9hZG1pbg==
  # Encodé en Base64 : minioadmin
  secret-key: bWluaW9hZG1pbg== 