apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-pvc
  namespace: exai
spec:
  accessModes:
    - ReadWriteOnce  # Le volume peut être monté en lecture/écriture par un seul nœud
  resources:
    requests:
      storage: 1Gi  # Demande 1 gigaoctet d'espace de stockage 