apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cet overlay se base sur ../../base
# Utilise 'resources' au lieu de 'bases' (corrigé)
resources:
  - ../../base/api-gateway/deployment.yaml
  - ../../base/api-gateway/gateway-secrets.yaml
  - ../../base/api-gateway/service.yaml
  # Utilisation de notre propre StatefulSet au lieu de celui de base
  # - ../../base/postgres/postgresql-statefulset.yaml
  - postgresql-statefulset.yaml
  - ../../base/postgres/postgresql-service.yaml
  - ../../base/service-selection/deployment.yaml
  - ../../base/service-selection/db-secrets.yaml
  - ../../base/service-selection/storage-secrets.yaml
  - ../../base/service-selection/service.yaml
  # - ../../base/service-selection/dataset-pvc.yaml # Supprimé car nous n'utilisons plus de PVC
  - ../../base/frontend/deployment.yaml
  - ../../base/frontend/service.yaml
  - ../../base/common/ingress.yaml
  - ../../base/common/letsencrypt-prod-issuer.yaml
  # Jobs de migration
  - ../../base/jobs/api-gateway-migration-job.yaml
  - ../../base/jobs/service-selection-migration-job.yaml

# Appliquer un namespace spécifique pour cet overlay
# (Redondant si la base le fait déjà, mais peut être utile pour surcharger)
# Décommenté pour forcer le déploiement dans le namespace 'ibis-x' sur Azure
namespace: ibis-x

# Remplacement des noms d'images spécifiques à Azure
# NOMS DYNAMIQUES - Remplacés automatiquement par le script de déploiement
images:
  - name: ibis-x-api-gateway
    newName: PLACEHOLDER_ACR.azurecr.io/ibis-x-api-gateway
  - name: service-selection
    newName: PLACEHOLDER_ACR.azurecr.io/service-selection
  - name: frontend
    newName: PLACEHOLDER_ACR.azurecr.io/frontend

# Patches pour les configurations spécifiques à Azure
patches:
  # Jobs de migration
  - path: migration-jobs-image-patch.yaml
    target:
      kind: Job
      name: api-gateway-migration-job
  - path: service-selection-migration-job-patch.yaml
    target:
      kind: Job
      name: service-selection-migration-job
  # Configuration stockage
  - path: storage-config-patch.yaml
    target:
      kind: Deployment
      name: service-selection
  # Auto-initialisation des vrais datasets en production
  - path: service-selection-auto-init-patch.yaml
    target:
      kind: Deployment
      name: service-selection-deployment

# Variables d'environnement spécifiques à Azure (si nécessaire)
# patchesStrategicMerge:
#   - azure-env-patch.yaml

# Configuration des replicas pour la production (via patches)
# Les replicas sont gérés via les patches dans les déploiements

# Tags pour toutes les images (sera remplacé dynamiquement)
commonLabels:
  environment: production
  deployment: azure
  managed-by: github-actions
