apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cet overlay se base sur ../../base
# Utilise 'resources' au lieu de 'bases' (corrigé)
resources:
  - ../../base

# Appliquer un namespace spécifique pour cet overlay
# (Redondant si la base le fait déjà, mais peut être utile pour surcharger)
# Décommenté pour forcer le déploiement dans le namespace 'exai' sur Azure
namespace: exai

# Remplacement des noms d'images spécifiques à Azure
images:
  - name: exai-api-gateway
    newName: exaimemoireacr.azurecr.io/exai-api-gateway
  - name: service-selection
    newName: exaimemoireacr.azurecr.io/service-selection
  - name: frontend
    newName: exaimemoireacr.azurecr.io/frontend
  # - name: postgres
  #   newName: exaimemoireacr.azurecr.io/postgres

# Suppression du patch ciblant l'ancien Deployment
# Patches pour les configurations spécifiques à Azure
# patches:
#   - path: postgresql-deployment-patch.yaml
#     target:
#       kind: Deployment
#       name: postgresql-deployment

# Ici, on pourrait ajouter des patches spécifiques à Azure si nécessaire plus tard
# (par exemple, pour modifier des variables d'environnement, des replicas, etc.)
# patches:
#   - path: deployment-patch.yaml
#     target:
#       kind: Deployment
#       name: my-deployment

# Important: Ne pas inclure explicitement les fichiers de secrets ou PVC ici
# s'ils sont déjà dans les dossiers référencés par 'resources'.
# Kustomize les prendra en compte automatiquement.
# Nous gérons les secrets manuellement sur AKS pour l'instant.