apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cet overlay se base sur ../../base
# Utilise 'resources' au lieu de 'bases' (corrigé)
resources:
  - ../../base/api-gateway/deployment.yaml
  - ../../base/api-gateway/gateway-secrets.yaml
  - ../../base/api-gateway/service.yaml
  # Utilisation de notre propre StatefulSet au lieu de celui de base
  # - ../../base/postgres/postgresql-statefulset.yaml
  - postgresql-statefulset.yaml
  - ../../base/postgres/postgresql-service.yaml
  - ../../base/service-selection/deployment.yaml
  - ../../base/service-selection/db-secrets.yaml
  - ../../base/service-selection/storage-secrets.yaml
  - ../../base/service-selection/service.yaml
  # - ../../base/service-selection/dataset-pvc.yaml # Supprimé car nous n'utilisons plus de PVC
  - ../../base/frontend/deployment.yaml
  - ../../base/frontend/service.yaml
  - ../../base/common/ingress.yaml
  - ../../base/common/letsencrypt-prod-issuer.yaml
  # Jobs de migration
  - ../../base/jobs/api-gateway-migration-job.yaml
  - ../../base/jobs/service-selection-migration-job.yaml

# Appliquer un namespace spécifique pour cet overlay
# (Redondant si la base le fait déjà, mais peut être utile pour surcharger)
# Décommenté pour forcer le déploiement dans le namespace 'ibis-x' sur Azure
namespace: ibis-x

# Remplacement des noms d'images spécifiques à Azure
images:
  - name: ibis-x-api-gateway
    newName: ibisprodacr.azurecr.io/ibis-x-api-gateway
  - name: service-selection
    newName: ibisprodacr.azurecr.io/service-selection
  - name: frontend
    newName: ibisprodacr.azurecr.io/frontend

# Patches pour les configurations spécifiques à Azure
patches:
  # Jobs de migration
  - path: migration-jobs-image-patch.yaml
    target:
      kind: Job
      name: api-gateway-migration-job
  - path: service-selection-migration-job-patch.yaml
    target:
      kind: Job
      name: service-selection-migration-job
  # Configuration stockage
  - path: storage-config-patch.yaml
    target:
      kind: Deployment
      name: service-selection
  # Auto-initialisation des vrais datasets en production
  - path: service-selection-auto-init-patch.yaml
    target:
      kind: Deployment
      name: service-selection-deployment

# Supprimer le patch pour le StatefulSet PostgreSQL puisque nous utilisons notre propre StatefulSet
# patches:
#   - path: postgresql-statefulset-patch.yaml
#     target:
#       kind: StatefulSet
#       name: postgresql
#       # Le namespace est déjà défini globalement pour l'overlay, pas besoin ici

# Important: Ne pas inclure explicitement les fichiers de secrets ou PVC ici
# s'ils sont déjà dans les dossiers référencés par 'resources'.
# Kustomize les prendra en compte automatiquement.
# Nous gérons les secrets manuellement sur AKS pour l'instant.
