apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cet overlay se base sur ../../base
# Utilise 'resources' au lieu de 'bases' (corrigé)
resources:
  - ../../base/api-gateway/deployment.yaml
  - ../../base/api-gateway/gateway-secrets.yaml
  - ../../base/api-gateway/service.yaml
  # Utilisation de notre propre StatefulSet au lieu de celui de base
  # - ../../base/postgres/postgresql-statefulset.yaml
  - postgresql-statefulset.yaml
  - ../../base/postgres/postgresql-service.yaml
  - ../../base/service-selection/deployment.yaml
  - ../../base/service-selection/db-secrets.yaml
  - ../../base/service-selection/service.yaml
  - ../../base/service-selection/dataset-pvc.yaml
  - ../../base/frontend/deployment.yaml
  - ../../base/frontend/service.yaml
  - ../../base/common/ingress.yaml
  - ../../base/common/letsencrypt-prod-issuer.yaml
  # Jobs de migration
  - ../../base/jobs/api-gateway-migration-job.yaml
  - ../../base/jobs/service-selection-migration-job.yaml

# Appliquer un namespace spécifique pour cet overlay
# (Redondant si la base le fait déjà, mais peut être utile pour surcharger)
# Décommenté pour forcer le déploiement dans le namespace 'exai' sur Azure
namespace: exai

# Remplacement des noms d'images spécifiques à Azure
images:
  - name: exai-api-gateway
    newName: exaiprodacr.azurecr.io/exai-api-gateway
  - name: api-gateway
    newName: exaiprodacr.azurecr.io/exai-api-gateway
  - name: service-selection
    newName: exaiprodacr.azurecr.io/service-selection
  - name: frontend
    newName: exaiprodacr.azurecr.io/frontend
  # - name: postgres
  #   newName: exaiprodacr.azurecr.io/postgres

# Patches pour les configurations spécifiques à Azure
# Supprimer la référence au patch oauth-redirect-patch.yaml
# patches:
#   - path: oauth-redirect-patch.yaml
#     target:
#       kind: Secret
#       name: gateway-secrets

# Suppression du patch ciblant l'ancien Deployment
# Patches pour les configurations spécifiques à Azure
# patches:
#   - path: postgresql-deployment-patch.yaml
#     target:
#       kind: Deployment
#       name: postgresql-deployment

# Patches spécifiques à Azure
patches:
  - path: migration-jobs-pullpolicy-patch.yaml
    target:
      kind: Job
      name: api-gateway-migration-job
  - path: migration-jobs-pullpolicy-patch.yaml
    target:
      kind: Job
      name: service-selection-migration-job

# Supprimer le patch pour le StatefulSet PostgreSQL puisque nous utilisons notre propre StatefulSet
# patches:
#   - path: postgresql-statefulset-patch.yaml
#     target:
#       kind: StatefulSet
#       name: postgresql
#       # Le namespace est déjà défini globalement pour l'overlay, pas besoin ici

# Important: Ne pas inclure explicitement les fichiers de secrets ou PVC ici
# s'ils sont déjà dans les dossiers référencés par 'resources'.
# Kustomize les prendra en compte automatiquement.
# Nous gérons les secrets manuellement sur AKS pour l'instant.