apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Référence la base commune
resources:
  - ../../base

# Appliquer un namespace spécifique pour cet overlay
namespace: ibis-x

# Remplacement automatique des noms d'images pour Azure
# NOMS DYNAMIQUES - Remplacés automatiquement par le script de déploiement
images:
  - name: ibis-x-api-gateway
    newName: ibisxprodacr6630.azurecr.io/ibis-x-api-gateway
  - name: service-selection
    newName: ibisxprodacr6630.azurecr.io/service-selection
  - name: frontend
    newName: ibisxprodacr6630.azurecr.io/frontend

# Patches pour les configurations spécifiques à Azure
patches:
  # PostgreSQL avec ressources pour production Azure
  - path: postgresql-statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: postgresql
  # Configuration complète des variables d'environnement Azure (remplace MinIO + auto-init)
  - path: complete-env-patch.yaml
    target:
      kind: Deployment
      name: service-selection

# Tags pour toutes les images (sera remplacé dynamiquement)
commonLabels:
  environment: production
  deployment: azure
  managed-by: scripts

