# migration-jobs-image-patch.yaml
# Patch pour utiliser la bonne image ACR et forcer le pull en production
- op: replace
  path: /spec/template/spec/containers/0/image
  # IMAGE DYNAMIQUE - Remplacée automatiquement par le script de déploiement
  value: ibisxprodacr6630.azurecr.io/ibis-x-api-gateway:latest
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always 
