# migration-jobs-image-patch.yaml
# Patch pour forcer le pull des images en production pour le job api-gateway-migration
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always 