apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: exai
  labels:
    app: postgresql
spec:
  serviceName: "postgresql-headless"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: remove-lost-found
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Checking for lost+found in /var/lib/postgresql/data..."
          rm -rf /var/lib/postgresql/data/lost+found
          echo "lost+found removed if it existed."
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgresql
        image: postgres:15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: tcp-postgresql
        env:
        - name: POSTGRES_DB
          value: exai_db
        - name: POSTGRES_USER
          value: exai_user
        - name: POSTGRES_PASSWORD
          value: password
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi 