# service-selection-migration-job-patch.yaml
# Patch pour utiliser la bonne image ACR et forcer le pull en production
- op: replace
  path: /spec/template/spec/containers/0/image
  # IMAGE DYNAMIQUE - Remplacée automatiquement par le script de déploiement
  value: PLACEHOLDER_ACR.azurecr.io/service-selection:latest
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always 
