# Kustomize patch pour la configuration Azure Blob Storage en environnement Azure
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-selection
  namespace: exai
spec:
  template:
    spec:
      containers:
      - name: service-selection
        env:
        - name: STORAGE_TYPE
          value: "azure"
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: azure-account-name
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: azure-account-key
        - name: STORAGE_BUCKET
          value: "exai-datasets" 