apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: exai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: exai-api-gateway:latest
        imagePullPolicy: Never
        envFrom:
          - secretRef:
              name: gateway-secrets
        ports:
        - containerPort: 8088
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
