# api-gateway-migration-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  # Nom du Job. Utiliser generateName pour éviter les conflits si relancé rapidement,
  # ou un nom fixe si géré par un pipeline qui supprime l'ancien job avant.
  # On utilise un nom fixe ici pour simplifier.
  name: api-gateway-migration-job
  namespace: exai # Assure-toi que c'est le bon namespace
spec:
  # ttlSecondsAfterFinished: 300 # Optionnel: Supprime le Job automatiquement après sa fin
  backoffLimit: 1 # Nombre de tentatives avant d'échouer
  template:
    spec:
      containers:
      - name: alembic-migration
        # Utilise l'image :latest (avec les mises en garde pour la prod)
        image: exaimemoireacr.azurecr.io/exai-api-gateway:latest
        imagePullPolicy: Always # Force la récupération de la dernière :latest
        command: ["alembic"]
        args: ["upgrade", "head"]
        workingDir: /app # Répertoire où se trouve alembic.ini
        env:
        # Définir explicitement DATABASE_URL à partir de la clé du secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: gateway-secrets # Nom du Secret
              key: database-url    # Nom de la clé DANS le Secret
        # Monte également les autres clés du secret si nécessaire (ex: SECRET_KEY si alembic/env.py l'utilise)
        # Si SECRET_KEY est aussi dans gateway-secrets avec la clé 'secret-key':
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: gateway-secrets
              key: secret-key # Assurez-vous que la clé est correcte dans le Secret
        # Optionnel: Si d'autres variables d'env sont nécessaires (ex: depuis ConfigMap)
        # - configMapRef:
        #     name: api-gateway-config
      restartPolicy: Never # Ne redémarre pas le pod en cas d'échec 