apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: exai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13 
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              value: "exai_db" 
            - name: POSTGRES_USER
              value: "exai_user" 
            - name: POSTGRES_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-persistent-storage
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc # Nom du PersistentVolumeClaim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: exai
spec:
  accessModes:
    - ReadWriteOnce # Mode d'accès standard pour une base de données
  resources:
    requests:
      storage: 1Gi # Taille du volume persistant (ajuster si besoin) 