apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: exai
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: exai-api-gateway
          imagePullPolicy: IfNotPresent
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: gateway-secrets
                key: database-url
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: gateway-secrets
                key: secret-key
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 30
