apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ibis-x
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ibis-x-api-gateway
          imagePullPolicy: Always
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: gateway-secrets
                key: database-url
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: gateway-secrets
                key: secret-key
          - name: GOOGLE_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: gateway-secrets
                key: google-client-id
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: gateway-secrets
                key: google-client-secret
          - name: OAUTH_REDIRECT_URL
            valueFrom:
              secretKeyRef:
                name: gateway-secrets
                key: oauth-redirect-url
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 30
