apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: exai # Assurez-vous que le namespace est correct
type: Opaque
data:
  # Clé secrète pour JWT (Base64 de 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7)
  secret-key: MDlkMjVlMDk0ZmFhNmNhMjU1NmM4MTgxNjZiN2E5NTYzYjkzZjcwOTlmNmYwZjRjYWE2Y2Y2M2I4OGU4ZDNlNw==
  # URL Base de données pour l'API Gateway (Base64 de postgresql+asyncpg://exai_user:password@postgresql-service.exai.svc.cluster.local:5432/exai_db)
  database-url: cG9zdGdyZXNxbCthc3luY3BnOi8vZXhhaV91c2VyOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5leGFpLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZXhhaV9kYg== 