apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: exai # Assurez-vous que le namespace est correct
type: Opaque
data:
  # Clé secrète pour JWT (Base64 de 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7)
  # CONSEIL: Dans un environnement de production, remplacer par une véritable clé générée de façon sécurisée
  secret-key: REPLACE_WITH_SECRET_KEY
  # URL Base de données pour l'API Gateway
  database-url: REPLACE_WITH_DATABASE_URL
  # Client ID Google OAuth
  google-client-id: REPLACE_WITH_GOOGLE_CLIENT_ID
  # Client Secret Google OAuth
  google-client-secret: REPLACE_WITH_GOOGLE_CLIENT_SECRET
  # URL de redirection OAuth par défaut (locale), encodée en Base64
  oauth-redirect-url: REPLACE_WITH_LOCAL_REDIRECT_URL
