apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: ibis-x
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
  type: ClusterIP
