apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Définit toutes les ressources de cette base
# Les overlays pourront se référer à cette base.
resources:
  # Common Resources (Ingress, Issuers, etc.)
  - common/ingress.yaml
  # - common/letsencrypt-staging-issuer.yaml # Supprimé/Commenté car on utilise Prod
  - common/letsencrypt-prod-issuer.yaml
  # API Gateway
  - api-gateway/deployment.yaml
  - api-gateway/gateway-secrets.yaml # Les valeurs seront surchargées si nécessaire par les overlays ou secrets manuels
  - api-gateway/service.yaml
  # Frontend
  - frontend/deployment.yaml
  - frontend/service.yaml
  # Postgres
  # Supprimer l'ancien déploiement
  # - postgres/postgresql-deployment.yaml
  # Ajouter les nouvelles ressources StatefulSet et Headless Service
  - postgres/postgresql-statefulset.yaml
  - postgres/postgresql-headless-service.yaml
  # Garder le service normal
  - postgres/postgresql-service.yaml
  # La gestion du PVC est maintenant intégrée au StatefulSet via volumeClaimTemplates
  # - postgres/postgresql-pvc.yaml # Inutile de lister le PVC explicitement
  # Service Selection
  - service-selection/deployment.yaml
  - service-selection/db-secrets.yaml # Les valeurs seront surchargées si nécessaire
  - service-selection/service.yaml
  - service-selection/dataset-pvc.yaml # Décommentez/vérifiez si besoin 