apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-celery-worker
  namespace: ibis-x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-pipeline-celery-worker
  template:
    metadata:
      labels:
        app: ml-pipeline-celery-worker
    spec:
      containers:
      - name: celery-worker
        image: ibis-x-ml-pipeline:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "app.tasks", "worker", "--loglevel=info", "--queues=ml_queue"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ml-pipeline-secrets
              key: database-url
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/0"
        - name: STORAGE_TYPE
          value: "minio"
        - name: MINIO_ENDPOINT
          value: "minio:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ml-pipeline-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ml-pipeline-secrets
              key: minio-secret-key
        - name: C_FORCE_ROOT
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - "celery"
            - "-A"
            - "app.tasks"
            - "inspect"
            - "ping"
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10 