apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline
  namespace: ibis-x
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: ml-pipeline 