apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Configuration temporaire pour déployer uniquement les jobs avec les patches minikube
namespace: ibis-x

resources:
  - api-gateway-migration-job.yaml
  - service-selection-migration-job.yaml
  - ml-pipeline-migration-job.yaml
  - service-selection-data-init-job.yaml
  - kaggle-dataset-import-job.yaml

# Patches spécifiques à Minikube pour les jobs (images locales)
patches:
  - path: migration-jobs-image-patch.yaml
    target:
      kind: Job
      name: api-gateway-migration-job
  - path: service-selection-migration-job-patch.yaml
    target:
      kind: Job
      name: service-selection-migration-job 