apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Référence la base commune (en ignorant les erreurs cert-manager)
resources:
  - ../../base

# Patches spécifiques à Minikube
patches:
  - path: postgresql-statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: postgresql
  - path: storage-config-patch.yaml  
  - path: minio-pvc-patch.yaml
  - path: migration-jobs-image-patch.yaml
    target:
      kind: Job
      name: api-gateway-migration-job
  - path: service-selection-migration-job-patch.yaml
    target:
      kind: Job
      name: service-selection-migration-job
  # Modifier l'ingress pour le local (sans SSL)
  - path: ingress-patch.yaml
  # Supprimer le ClusterIssuer (cert-manager) pour le local
  - target:
      kind: ClusterIssuer
      name: letsencrypt-prod
    patch: |-
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-prod
      $patch: delete

# (Optionnel) Vous pouvez aussi ajouter des préfixes/suffixes aux noms,
# définir des namespaces, etc.
# namespace: ibis-x-minikube
# namePrefix: minikube- 
