apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Référence la base commune
resources:
  - ../../base

# Applique les patches spécifiques à Minikube (syntaxe moderne)
patches:
  - path: postgresql-statefulset-patch.yaml
  - path: storage-config-patch.yaml  
  - path: minio-pvc-patch.yaml
  - path: migration-jobs-image-patch.yaml  # Patch pour les images locales des jobs de migration
  # Ajoutez ici d'autres patches spécifiques à Minikube si nécessaire

# (Optionnel) Vous pouvez aussi ajouter des préfixes/suffixes aux noms,
# définir des namespaces, etc.
# namespace: ibis-x-minikube
# namePrefix: minikube- 
