apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  # Configuration Minikube complète
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
  volumeClaimTemplates:
    # Le nom doit correspondre à celui dans la base (postgresql-data)
    # On ne patch que le storageClassName
    - metadata:
        name: postgresql-data
      spec:
        storageClassName: standard # Valeur spécifique pour Minikube 
