name: Build and Push Production Images

on:
  push:
    branches:
      - production

env:
  AZURE_CONTAINER_REGISTRY: 'exaimemoireacr'
  API_GATEWAY_IMAGE_NAME: 'exai-api-gateway'
  SERVICE_SELECTION_IMAGE_NAME: 'service-selection'
  FRONTEND_IMAGE_NAME: 'frontend'

jobs:
  build_and_push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Obtenir le SHA court du commit pour le tag
      - name: Get short SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Installer Skaffold
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/
          skaffold version

      # Builder et pusher chaque image
      - name: Build and push API Gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.API_GATEWAY_IMAGE_NAME }}:${{ env.sha_short }}

      - name: Build and push Service Selection image
        uses: docker/build-push-action@v5
        with:
          context: ./service-selection
          file: ./service-selection/Dockerfile
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.SERVICE_SELECTION_IMAGE_NAME }}:${{ env.sha_short }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.sha_short }}
          build-args: |
            ANGULAR_ENV=production

      - name: Print deployment instructions
        run: |
          echo "Images have been built and pushed successfully!"
          echo "To deploy to AKS, run the following commands:"
          echo "az login"
          echo "az acr login --name exaimemoireacr"
          echo "az aks get-credentials --resource-group exai-production-rg --name exai-prod-aks"
          echo "skaffold deploy --profile=azure --tag=${{ env.sha_short }} -n exai"